import { routing } from "@/i18n/routing";

import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import type React from "react";

import { Navigation } from "@/components/navigation";
import { ReduxProvider } from "@/redux/provider";
import { ReactQueryProvider } from "@/services/react-query/provider";
import { Language } from "@/libs/types/language";
import "@/styles/globals.css";
import { ThemeProviders } from "@/theme/provider";
import { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { cookies } from "next/headers";
import { Theme } from "@/theme/types";
import { SessionStorageKeys } from "@/libs/constants/keys";
import { SessionProviders } from "@/components/provider/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Language)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages({ locale: locale as Language });

  const cookieStore = await cookies();
  const theme = (cookieStore.get(SessionStorageKeys.THEME)?.value as Theme) || Theme.LIGHT;

  return (
    <html
      lang={locale}
      className={theme}
      style={{ colorScheme: theme }}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ReactQueryProvider>
            <NextIntlClientProvider messages={messages}>
              <ThemeProviders theme={theme}>
                <SessionProviders>
                  <Navigation />
                  <main className="container mx-auto px-4 py-8">{children}</main>
                </SessionProviders>
              </ThemeProviders>
            </NextIntlClientProvider>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
